Histogram
js-tasks-ru/htmlcss-20221107_germanium312 pull request #12
Opened 2022-11-28 19:18 UTC by germakis

2022-11-28 19:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-28 23:22 UTC, GSemikozov requested changes

2022-11-28 23:22 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +	min-height: 106px; /*del.*/
лишнее

2022-11-28 23:22 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +	padding-bottom: 39px;
margin (внешнее поведение, "отталкиваемся" от соседа)

2022-11-28 23:22 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__info-link a {
селекторы тегов не используем, лишний враппер для ссылки не нужен, можно класс сразу вешать на `<a>`

2022-11-28 23:22 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +	max-height: 50px;
лишнее

2022-11-28 23:22 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +	width: 9px;
лучше flex-basis: 9px или flex-grow: 1

2022-11-29 17:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-29 18:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-12-05 14:54 UTC, GSemikozov approved these changes

2022-12-05 14:55 UTC, merged