Создана новая ветка с окончанием "2" из мастера
js-tasks-ru/htmlcss-20221107_germanium312 pull request #6
Opened 2022-11-17 18:05 UTC by germakis

Создана новая ветка с окончанием "2" из мастера и скопированы файлы

2022-11-17 18:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-18 10:34 UTC, GSemikozov requested changes

2022-11-18 10:34 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.container__buttons {
в файле стилей блока можно описывать классы блока и его элементов и модификаторов. В данном случае блок контейнер не относится к блоку кнопка, тем более - его элементы. Если нужны какие-то вспомогательные стили только для текущей задачи - такие стили можно писать в тег style прямо на хтмл странице

2022-11-18 10:34 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +	padding: 15px 65.58px 14px 66.42px;
дробные пиксели лучше не использовать, можно оставить 15px по краям

2022-11-18 10:34 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +	background: var(--primary);
фон и цвет бордера как primary лучше добавлять сразу на primary

2022-11-18 10:34 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary-disabled,
disabled будет общим для всех типов, то есть просто .button:disabled, и желательно добавить pointer-events: none

2022-11-18 10:34 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_secondary-disabled {
удалим

2022-11-18 10:34 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_alternate-disabled {
удалим

2022-11-18 10:34 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +            <button class="button button_primary-disabled" disabled>Primary disabled</button>
button_primary-disabled -> button_primary

2022-11-20 14:09 UTC, GSemikozov requested changes

2022-11-20 14:09 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +	padding: 15px;
по дизайну там разница в 1px, надо обратить внимание (`15px 15px 14px`)

2022-11-20 14:09 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +	cursor: not-allowed;
pointer-events: none; по умолчанию ставит курсор в default, так что cursor: not-allowed; можно удалить

2022-11-20 15:56 UTC, germakis commented
Спасибо за такие тонкие моменты)

2022-11-21 20:49 UTC, GSemikozov approved these changes

2022-11-21 20:49 UTC, merged